// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as Vitest$1 from "vitest";

Vitest.test("Math.sqrt()", undefined, (function (t) {
        t.assertions(3);
        Vitest$1.expect(Math.sqrt(4.0)).toBe(2.0);
        Vitest$1.expect(Math.sqrt(144.0)).toBe(12.0);
        Vitest$1.expect(Math.sqrt(2.0)).toBe(Math.SQRT2);
      }));

Vitest.test("JSON", undefined, (function (param) {
        var input = {
          foo: "hello",
          bar: "world"
        };
        var output = JSON.stringify(input);
        Vitest$1.expect(output).eq("{\"foo\":\"hello\",\"bar\":\"world\"}");
        Vitest.Assert.deepEqual("matches original", JSON.parse(output), input);
      }));

export {
  
}
/*  Not a pure module */
